/** Series / project category presets (create form + filters). Backend stores free text. */
export const PROJECT_CATEGORY_OPTIONS = [
  "Drama",
  "Action",
  "Romantic",
  "Comedy",
  "Sci-Fi",
  "Thriller",
  "Horror",
  "Fantasy",
  "Mystery",
  "Crime",
  "Historical",
  "Adventure",
  "Animation",
  "Family",
  "Documentary",
  "Biography",
  "War",
  "Western",
  "Musical",
  "Sports",
  "Reality TV",
  "Soap opera",
  "Miniseries",
  "Anthology",
];
